### ISSUE TITLE
Integrate Deployment Tracking

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-react-pouchdb#13]
Integrate deployment tracking with the new metrics tracker maintained by the Digital Business Group.

**Comment by bradley-holt** [comment]
I suspect that metrics tracking is not integrated correctly, but I am not certain. I am not familiar enough with React to know for sure, but I suspect that `src/App.js` is frontend code and that the tracking code does not belong there. The tracking code is intended to be executed during runtime on the backend. See #47.

Can you take a look at this, @glynnbird?

**Comment by glynnbird** [comment]
Sure.

**Comment by isc-rsingh** [comment]
Yes `src/App.js` is front-end code. Tracking should happen on the web server, which is run by the create-react-app scripts (reference: https://github.com/facebook/create-react-app). Integrating anything into that will be difficult.
