### ISSUE TITLE
README "Privacy Notice" Section

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-react-pouchdb#20]
Using the [README template](https://github.com/ibm-watson-data-lab/shopping-list/blob/master/templates/README.md) for reference, update the "Privacy Notice" section of the README as needed.

**Comment by lornajane** [comment]
Let's review this once the blocking issues (i.e. the actual deployment and metrics tracking) have been implemented

**Comment by bradley-holt** [comment]
Confirmed that this has been updated in accordance with the deployment tracking changes.
