### ISSUE TITLE
README "Tutorial" Section

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-react-pouchdb#21]
Add a tutorial section to the README, if applicable, which says:

>Refer to the [tutorial](https://github.com/ibm-watson-data-lab/shopping-list-react-pouchdb/blob/master/tutorial) for step-by-step instructions on how to build your own Offline First shopping list Progressive Web App with React and PouchDB.

**Comment by terichadbourne** [comment]
Confirmed with Raj that there is no tutorial to add, so I am closing this without adding a tutorial section to the readme
