### ISSUE TITLE
React build error

### ISSUE THREAD

**Issue by glynnbird** [ibm-watson-data-lab/shopping-list-react-pouchdb#28]
I get a react build error when checking out this repository and running `npm run build`:

```
Creating an optimized production build...
Failed to compile.

static/js/main.edbc7407.js from UglifyJs
Name expected [./~/ibm-shopping-list-model/src/ShoppingListFactory.js:5,0][static/js/main.edbc7407.js:16628,6]
```

**Comment by isc-rsingh** [comment]
@bradley-holt I seem to remember that this might have something to do with ES6 vs. ES5 incompatibility regarding this app and ibm-shopping-list-model? Does that sound right?

**Comment by bradley-holt** [comment]
@rajrsingh It appears that this issue has been resolved with 1793a66bbb577fa20521e7cf040e67d3d10a436c and 13504b047f3cb471d65cb601f1ac0751fb70e077. Can you confirm?

**Comment by isc-rsingh** [comment]
No @bradley-holt that fixes production deployment but breaks development (with `npm start`). Developer has to toggle between the two methods to do both things. I don't want to take up half the sprint researching a fix. I think we hoped the problem would "go away" with module evolution. I think you couldn't move to ES6 completely was because of cuid module?

**Comment by isc-rsingh** [comment]
Hey @bradley-holt my gut feeling was that the applitude dependency in cuid was the problem. Looks like it may have been fixed 20 days ago: https://github.com/ericelliott/cuid/issues/41. Want to upgrade cuid module to use v2.0.2 in ibm-shopping-list-model? Maybe my procrastination on this issue has paid off ;)

**Comment by bradley-holt** [comment]
@rajrsingh I've published v0.3.0 which now uses cuid v2.0.2 if you want to give that a try.

**Comment by glynnbird** [comment]
I'm still seeing an error with v0.3.0 of the domain model:

```
$ npm run build

> shopping-list-react-pouchdb@0.1.0 build /Users/glynnb/projects/shopping-list-react-pouchdb
> react-scripts build

Creating an optimized production build...
Failed to compile.

static/js/main.b2f79008.js from UglifyJs
Name expected [./~/ibm-shopping-list-model/src/ShoppingListFactory.js:5,0][static/js/main.b2f79008.js:16925,6]
```

**Comment by glynnbird** [comment]
Build works on Node 8.9, not on Node 7.10

**Comment by vabarbosa** [comment]
@rajrsingh this should be resolved with an updated `shopping-list-model-js`
see: https://github.com/ibm-watson-data-lab/shopping-list-model-js/pull/20

**Comment by bradley-holt** [comment]
This looks like it's been resolved to me.
