### ISSUE TITLE
metrics tracker breaks app at runtime

### ISSUE THREAD

**Issue by isc-rsingh** [ibm-watson-data-lab/shopping-list-react-pouchdb#47]
@bradley-holt reports we need an updated version of `global-prefix` per https://github.com/jonschlinkert/global-prefix/issues/7

`find-file-up` module is requiring ^0.1.4 which is probably preventing an update to 1.x.x

**Comment by bradley-holt** [comment]
Simply removing the following tracking code from `src/App.js` resolves this issue:

    require('metrics-tracker-client').track()

I am not familiar enough with React to know for sure, but I suspect that `src/App.js` is frontend code and that the tracking code does not belong there anyways. The tracking code is intended to be executed during runtime on the backend.
