### ISSUE TITLE
Readme: content for section "Running the tests" is missing

### ISSUE THREAD

**Issue by ptitzler** [ibm-watson-data-lab/shopping-list-react-pouchdb#55]
The section is currently marked as (UPDATE AS NEEDED)

**Comment by bradley-holt** [comment]
@ptitzler This section is addressed in issue #19 and PR #52 (which has not yet been merged).

**Comment by vabarbosa** [comment]
can be closed once PR #52 has been merged

**Comment by bradley-holt** [comment]
LGTM.
