### ISSUE TITLE
Readme: content for section "Deploying to GitHub Pages" is missing

### ISSUE THREAD

**Issue by ptitzler** [ibm-watson-data-lab/shopping-list-react-pouchdb#56]
Section: Deploying to GitHub Pages (UPDATE AS NEEDED)

I therefore had to guess how to do that and couldn't verify that the deployment actually works.

**Comment by bradley-holt** [comment]
@ptitzler This section is addressed in issue #19 and PR #52 (which has not yet been merged).

**Comment by vabarbosa** [comment]
can be closed once PR #52 has been merged

**Comment by bradley-holt** [comment]
LGTM.
