### ISSUE TITLE
IBM Code Patterns Review

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-react-pouchdb#62]
Review to ensure compliance with IBM Code Pattern standards, compliance with our team's established standards for these demo apps, and overall quality.

**Comment by ptitzler** [comment]
- Reviewed README
- Reviewed MAINTAINERS
- Reviewed CONTRIBUTING
- Tested running locally
- Tested deploying/running on the cloud
- Tested running tests
- Tested deploying to GitHub pages
